// datav/codes/code/course-full/module_07/lesson_07.07/code/draft/src/Chart/Chart.jsx
import React, { createContext, useContext } from "react"
import { dimensionsPropsType } from "./utils"

import "./Chart.css"

const ChartContext = createContext()
export const useDimensionsContext = () => useContext(ChartContext)

const Chart = ({ dimensions, children }) => (
  <ChartContext.Provider value={dimensions}>
    <svg className="Chart" width={dimensions.width} height={dimensions.height}>
      <g transform={`translate(${
        dimensions.marginLeft
      }, ${
        dimensions.marginTop
      })`}>
        { children }
      </g>
    </svg>
  </ChartContext.Provider>
)

Chart.propTypes = {
  dimensions: dimensionsPropsType,
}

Chart.defaultProps = {
  dimensions: {},
}

export default Chart

// datav/codes/code/course-full/module_07/lesson_07.11/code/end/src/completed/Chart/Chart.svelte
<script>
  import { onMount, setContext } from "svelte";
  import { writable } from "svelte/store";

  export let dimensions = {};

  let currentDimensions = writable(dimensions)
  $: {
    currentDimensions.set(dimensions)
  }
  setContext("Chart", {
    dimensions: currentDimensions
  });

</script>

<svg class="Chart" width={dimensions.width} height={dimensions.height}>
  <g transform={`translate(${dimensions.marginLeft}, ${dimensions.marginTop})`}>
    <slot />
  </g>
</svg>
