// datav/codes/code/course-full/module_07/lesson_07.04/code/end/src/Timeline.jsx
import React from "react"
import PropTypes from "prop-types"
import * as d3 from "d3"

import Chart from "./Chart/Chart"
import Line from "./Chart/Line"
import Axis from "./Chart/Axis-naive"
import { useChartDimensions, accessorPropsType } from "./Chart/utils";

const formatDate = d3.timeFormat("%-b %-d")

const Timeline = ({ data, xAccessor, yAccessor, label }) => {
  const [ref, dms] = useChartDimensions()

  return (
    <div className="Timeline" ref={ref}>
      <Chart dimensions={dms}>
      </Chart>
    </div>
  )
}

Timeline.propTypes = {
  data: PropTypes.array,
  xAccessor: accessorPropsType,
  yAccessor: accessorPropsType,
  label: PropTypes.string,
}

Timeline.defaultProps = {
  xAccessor: d => d.x,
  yAccessor: d => d.y,
}

export default Timeline

// datav/codes/code/course-full/module_07/lesson_07.11/code/draft/src/Timeline.svelte
<script>
  import * as d3 from "d3";

  import Chart from "./Chart/Chart.svelte";
  import Line from "./Chart/Line.svelte";
  import Axis from "./Chart/Axis-naive.svelte";

  const formatDate = d3.timeFormat("%-b %-d");

  export let data = [];
  export let xAccessor = d => d.x;
  export let yAccessor = d => d.y;
  export let label;

</script>

<div class="Timeline placeholder">
</div>

<style>
  .Timeline {
    height: 300px;
    min-width: 500px;
    width: calc(100% + 1em);
    margin-bottom: 2em;
  }
</style>
