// docs/datav/codes/code/course-full/module_07/lesson_07.08/code/mid/src/Chart/Axis-naive.jsx
import React, {useRef} from "react"
import PropTypes from "prop-types"
import * as d3 from 'd3'

import { useDimensionsContext } from "./Chart"

const Axis = ({ dimension, scale, ...props }) => {
  const dimensions = useDimensionsContext()
  const ref = useRef()

  const axisGeneratorsByDimension = {
    x: "axisBottom",
    y: "axisLeft",
  }
  const axisGenerator = d3[axisGeneratorsByDimension[dimension]]()
    .scale(scale)

  if (ref.current) {
    d3.select(ref.current)
      .transition()
      .call(axisGenerator)
  }

  return (
    <g {...props}
      className="Axis"
      ref={ref}
      transform={
        dimension == "x"
          ? `translate(0, ${
            dimensions.boundedHeight
          })`
          : null
      }
    />
  )
}

Axis.propTypes = {
  dimension: PropTypes.oneOf(["x", "y"]),
  scale: PropTypes.func,
}

const formatNumber = d3.format(",")
Axis.defaultProps = {
  dimension: "x",
}

export default Axis

// datav/codes/code/course-full/module_07/lesson_07.11/code/draft/src/completed/Chart/Axis-naive.svelte
<script>
  import { getContext } from "svelte";
  import * as d3 from "d3";

  export let dimension = "x";
  export let scale = null;
  export let label;
  export let formatTick = d3.format(",");

  const { dimensions: dimensionsStore } = getContext("Chart");
  $: dimensions = $dimensionsStore;

  const axisGeneratorsByDimension = {
    x: "axisBottom",
    y: "axisLeft",
  }
  const axisGenerator = d3[axisGeneratorsByDimension[dimension]]()
    .scale(scale)
    .tickFormat(formatTick)

  let ref
  if (ref) {
    d3.select(ref)
      .transition()
      .call(axisGenerator)
  }
</script>

<g bind:this={ref}
  class="Axis Axis--dimension-{dimension}"
  transform={`translate(0, ${dimensions.boundedHeight})`}>
</g>
