// datav/codes/code/course-full/module_07/lesson_07.08/code/end/src/Chart/Axis.jsx
import React from "react"
import PropTypes from "prop-types"
import * as d3 from 'd3'
import { dimensionsPropsType } from "./utils";
import { useDimensionsContext } from "./Chart";

const axisComponentsByDimension = {
  x: AxisHorizontal,
  y: AxisVertical,
}
const Axis = ({ dimension, ...props }) => {
  const dimensions = useDimensionsContext()
  const Component = axisComponentsByDimension[dimension]
  if (!Component) return null

  return (
    <Component {...props}
      dimensions={dimensions}
    />
  )
}

Axis.propTypes = {
  dimension: PropTypes.oneOf(["x", "y"]),
  dimensions: dimensionsPropsType,
  scale: PropTypes.func,
  label: PropTypes.string,
  formatTick: PropTypes.func,
}

const formatNumber = d3.format(",")
Axis.defaultProps = {
  dimension: "x",
  scale: null,
  formatTick: formatNumber,
}

export default Axis


function AxisHorizontal ({ dimensions, label, formatTick, scale, ...props }) {
  const numberOfTicks = dimensions.boundedWidth < 600
      ? dimensions.boundedWidth / 100
      : dimensions.boundedWidth / 250

  const ticks = scale.ticks(numberOfTicks)

  return (
    <g className="Axis AxisHorizontal" {...props} transform={`translate(0, ${
      dimensions.boundedHeight
    })`}>
      <line
        className="Axis__line"
        x2={dimensions.boundedWidth}
      />
      {ticks.map((tick, i) => (
        <text
          key={i}
          className="Axis__tick"
          transform={`translate(${scale(tick)}, 25)`}
        >
          { formatTick(tick) }
        </text>
      ))}
      {label && (
        <text
          className="Axis__label"
          transform={`translate(${
            dimensions.boundedWidth / 2
          }, 60)`}
        >
          { label }
        </text>
      )}
    </g>
  )
}

function AxisVertical (
  { dimensions, label, formatTick, scale, ...props }
) {
  const numberOfTicks = dimensions.boundedHeight / 70

  const ticks = scale.ticks(numberOfTicks)

  return (
    <g className="Axis AxisVertical" {...props}>
      <line
        className="Axis__line"
        y2={dimensions.boundedHeight}
      />

      {ticks.map((tick, i) => (
        <text
          key={tick}
          className="Axis__tick"
          transform={`translate(-16, ${scale(tick)})`}
        >
          { formatTick(tick) }
        </text>
      ))}

      {label && (
        <text
          className="Axis__label"
          style={{
            transform: `translate(-56px, ${
              dimensions.boundedHeight / 2
            }px) rotate(-90deg)`
          }}
        >
          { label }
        </text>
      )}
    </g>
  )
}

// datav/codes/code/course-full/module_07/lesson_07.11/code/draft/src/completed/Chart/Axis.svelte
<script>
  import { getContext } from "svelte";
  import * as d3 from "d3";

  export let dimension = "x";
  export let scale = null;
  export let label;
  export let formatTick = d3.format(",");

  const { dimensions: dimensionsStore } = getContext("Chart");
  $: dimensions = $dimensionsStore;

  $: numberOfTicks =
    dimension == "x"
      ? dimensions.boundedWidth < 600
        ? dimensions.boundedWidth / 100
        : dimensions.boundedWidth / 250
      : dimensions.boundedHeight / 70;

  $: ticks = scale.ticks(numberOfTicks);
</script>

<g
  class="Axis Axis--dimension-{dimension}"
  transform={`translate(0, ${dimension == "x" ? dimensions.boundedHeight : 0})`}>
  <line
    class="Axis__line"
    x2={dimension == "x" ? dimensions.boundedWidth : 0}
    y2={dimension == "y" ? dimensions.boundedHeight : 0}
  />

  {#each ticks as tick, i}
    <text class="Axis__tick" transform={`translate(${(
      dimension == "x"
        ? [scale(tick), 25]
        : [-16, scale(tick)]
      ).join(", ")})`}>
      {formatTick(tick)}
    </text>
  {/each}

  {#if label}
    <text
      class="Axis__label"
      style="transform: translate({(
        dimension == "x"
          ? [dimensions.boundedWidth / 2, 60]
          : [-56, dimensions.boundedHeight / 2]
      ).map(d => d + "px").join(", ")}) {
        dimension == "y" ? "rotate(-90deg)" : ""
      }">
      {label}
    </text>
  {/if}
</g>

<style>
  .Axis__line {
    stroke: #bdc3c7;
  }

  .Axis__label {
    text-anchor: middle;
    font-size: 0.8em;
    letter-spacing: 0.01em;
  }

  .Axis__tick {
    font-size: 0.9em;
    transition: all 0.3s ease-out;
  }

  .Axis--dimension-x .Axis__tick {
    text-anchor: middle;
  }

  .Axis--dimension-y .Axis__tick {
    dominant-baseline: middle;
    text-anchor: end;
  }
</style>
